### ISSUE TITLE
Julia ML ecosystem

### ISSUE THREAD

**Issue by datnamer** [JuliaTakingFittingAPIsSeriously/Roadmap#4]
https://github.com/JuliaML Holds a great deal of design and engineering work towards the goals of this org. Have you considered taking or forking from there? 

Specifically https://github.com/JuliaML/LearnBase.jl is the base package. @evizero would know more.

**Comment by oxinabox** [comment]
I think I might be JuliaML's biggest fan :-P

The stuff I am playing with in 
https://github.com/JuliaTakingFittingAPIsSeriously/Roadmap/blob/master/Demo-traits.ipynb
is based on LearnBase.jl


It forms part of the solution space for sure

**Comment by datnamer** [comment]
Cool!
